Repository OpenNebula/one, pull requests merged in 2019-01, with the labels that each got.

#2513 F #2476: Erasure-coded Ceph VM images forget about being erasure-coded after restoring a snapshot
  src/datastore_mad/remotes/ceph/snap_revert
  src/tm_mad/ceph/snap_revert
Labels: Category: Drivers - Storage

#2670 Feature 2650
  src/vmm_mad/remotes/kvm/poll
Labels: Category: Drivers - Monitor

#2780 F #1684 handle disk TYPE=BLOCK for LxD containers
  src/vmm_mad/remotes/lib/lxd/container.rb
  src/vmm_mad/remotes/lib/lxd/mapper/mapper.rb
  src/vmm_mad/remotes/lib/lxd/mapper/raw.rb
Labels: Category: Drivers - VM, Status: Accepted
